spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  application:
    name: order
server:
  port: 8081


